### ISSUE TITLE
Bug: the following code breaks the prsr

### ISSUE THREAD

**Issue by Tibing** [akveo/doc-prsr#10]
https://github.com/tibing/nebular/tree/feature/popover

**Comment by nnixaa** [comment]
@Tibing could you be more specific please?

**Comment by Tibing** [comment]
Thrown error:

```

> nebular@2.0.0-rc.4 docs:serve /Users/n.poltoratsky/Projects/Akveo/nebular
> npm run docs:parse && npm run docs:start


> nebular@2.0.0-rc.4 docs:parse /Users/n.poltoratsky/Projects/Akveo/nebular
> gulp docs

[11:15:10] Using gulpfile ~/Projects/Akveo/nebular/gulpfile.js
[11:15:10] Starting 'generate-doc-json'...
[11:15:10] 
TypeDoc 0.7.1
Using TypeScript 2.3.2 from /Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/typedoc/node_modules/typescript/lib

[11:15:13] Cannot find global type 'Array'.
[11:15:13] Cannot find global type 'Boolean'.
[11:15:13] Cannot find global type 'Function'.
[11:15:13] Cannot find global type 'IArguments'.
[11:15:13] Cannot find global type 'Number'.
[11:15:13] Cannot find global type 'Object'.
[11:15:13] Cannot find global type 'RegExp'.
[11:15:13] Cannot find global type 'String'.
[11:15:13] Finished 'generate-doc-json' after 3.02 s
[11:15:13] Starting 'docs'...
[11:15:13] 'docs' errored after 142 ms
[11:15:13] Error: Command failed: prsr -g typedoc -f angular -i docs/docs.json -o docs/output.json
/Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/doc-prsr/dist/typedoc.parser/parsers/properties.parser.js:82
        return prop[typedoc_parser_options_1.CO.type][typedoc_parser_options_1.CO.name] + '<' + prop[typedoc_parser_options_1.CO.type][typedoc_parser_options_1.CO.typeArguments][0][typedoc_parser_options_1.CO.name] + '>';
                                                                                                                                                                                 ^

TypeError: Cannot read property '0' of undefined
    at PropertiesParser.getTypeReferenceProp (/Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/doc-prsr/dist/typedoc.parser/parsers/properties.parser.js:82:178)
    at PropertiesParser.getType (/Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/doc-prsr/dist/typedoc.parser/parsers/properties.parser.js:67:31)
    at PropertiesParser.parseProperty (/Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/doc-prsr/dist/typedoc.parser/parsers/properties.parser.js:40:24)
    at /Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/doc-prsr/dist/typedoc.parser/parsers/properties.parser.js:17:38
    at Array.map (<anonymous>)
    at PropertiesParser.getProps (/Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/doc-prsr/dist/typedoc.parser/parsers/properties.parser.js:14:18)
    at TypedocParser.parseClass (/Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/doc-prsr/dist/typedoc.parser/typedoc.parser.js:70:31)
    at /Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/doc-prsr/dist/typedoc.parser/typedoc.parser.js:30:34
    at Array.map (<anonymous>)
    at TypedocParser.getClasses (/Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/doc-prsr/dist/typedoc.parser/typedoc.parser.js:27:14)

    at checkExecSyncError (child_process.js:598:13)
    at execSync (child_process.js:638:13)
    at Gulp.parseSassThemes (/Users/n.poltoratsky/Projects/Akveo/nebular/gulpfile.js:219:3)
    at module.exports (/Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/orchestrator/index.js:214:10)
    at /Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/orchestrator/index.js:279:18
    at finish (/Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/n.poltoratsky/Projects/Akveo/nebular/node_modules/end-of-stream/node_modules/once/once.js:17:25)
```

**Comment by serkon** [comment]
Same error acquired for me. I found location 

<sub>file: node_modules/doc-prsr/dist/typedoc.parser/parsers/methods.parser.js</sub>
```js
MethodsParser.prototype.parseTypeFromSignature = function (obj) {
        var _this = this;
        var mainReturnedType = this.determineType(obj[typedoc_parser_options_1.CO.type][typedoc_parser_options_1.CO.declaration][typedoc_parser_options_1.CO.signatures][0]);C
        var parameters = [];
        obj[typedoc_parser_options_1.CO.type][typedoc_parser_options_1.CO.declaration][typedoc_parser_options_1.CO.signatures][0][typedoc_parser_options_1.CO.parameters].forEach(function (item) {
            parameters.push(item[typedoc_parser_options_1.CO.name] + ': ' + _this.determineType(item));
        });
        var returnedTypePrepared = '';
        parameters.forEach(function (item) {
            returnedTypePrepared += item.toString() + ', ';
        });
        return ('(' + returnedTypePrepared + ') => ' + mainReturnedType).replace(/, \)/g, ')');
    };
```


I guess, Given`obj` parameter is not contains `typedoc_parser_options_1` property. So it returned an error.


<sub>`obj` is </sub>
```json
{
  "id": 1606,
  "name": "makeFilterToObject",
  "kind": 4096,
  "kindString": "Call signature",
  "flags": {},
  "parameters": [
    {
      "id": 1607,
      "name": "filter",
      "kind": 32768,
      "kindString": "Parameter",
      "flags": {},
      "type": {
        "type": "array",
        "elementType": {
          "type": "reference",
          "name": "TableFilter",
          "id": 1368,
          "typeArguments": [
            {
              "type": "intrinsic",
              "name": "any"
            }
          ]
        }
      }
    },
    {
      "id": 1608,
      "name": "row",
      "kind": 32768,
      "kindString": "Parameter",
      "flags": {
        "isOptional": true
      },
      "type": {
        "type": "intrinsic",
        "name": "any"
      }
    }
  ],
  "type": {
    "type": "reflection",
    "declaration": {
      "id": 1609,
      "name": "__type",
      "kind": 65536,
      "kindString": "Type literal",
      "flags": {}
    }
  }
}
```
